n = input('Escreva algo: ')
print('O tipo primitivo desse valor é: ', type(n))
print('Tem espaço?', n.isspace())
print('É decimal?', n.isdecimal())
print('É alfanumérico?', n.isalnum())
print('É alfabético?', n.isalpha())
print('É ASCII?', n.isascii())
print('É dígito?', n.isdigit())
print('É identificador?', n.isidentifier())
print('É minúsculo?', n.islower())
print('É imprimível?', n.isprintable())
print('É título?', n.istitle())
print('É maiúsculo?', n.isupper())
print('É numérico?', n.isnumeric())
