frase = str(input('Escreva sua frase: ')).upper()
print('Analizando a letra "A"... ')
print('A letra "A" aparece {} vezes na frase'.format(frase.count('A')))
print('A primeira letra "A" apareceu na posição {} '.format(frase.find('A')+1))
print('A ultima letra "A" apareceu na posição {} '.format(frase.rfind('A')+1))
